development: 
  adapter: postgresql
  database: myapp_dev
  encoding: utf8
  host: localhost
  username: somedevusername
  password: somepassword

test:
  adapter: postgresql
  database: myapp_test
  encoding: utf8
  host: localhost
  username: somedevusername
  password: somepassword

production:
  adapter: postgresql
  url: <%= ENV['POSTGRESQL_URL'] %> #This is the environment variable created by our Dokku command earlier
  encoding: unicode
  pool: 5
